FROM golang:1.16.5-stretch as build

LABEL maintainer="Alex Cordeiro <alexc@diamnet.org>"

EXPOSE 5432
EXPOSE 8000

ADD . /src/ticker
WORKDIR /src/ticker
RUN go build -o /opt/diamnet/bin/ticker ./services/ticker/

WORKDIR /src/ticker/services/ticker/docker/
RUN ["chmod", "+x", "./dependencies"]
RUN ["./dependencies"]
RUN ["chmod", "+x", "setup"]
RUN ["./setup"]
RUN ["cp", "-r", "conf", "/opt/diamnet/conf"]
RUN ["crontab", "-u", "diamnet", "/opt/diamnet/conf/crontab.txt"]
RUN ["chmod", "+x", "start"]

ENTRYPOINT ["/src/ticker/services/ticker/docker/start"]
