#!/usr/bin/env bash
set -e

useradd --uid 10011001 --home-dir /home/diamnet --no-log-init diamnet \
    && mkdir -p /home/diamnet \
    && chown -R diamnet:diamnet /home/diamnet

mkdir -p /opt/diamnet/bin
mkdir -p /opt/diamnet/www
chown -R diamnet:diamnet /opt/diamnet/www
mkdir -p /opt/diamnet/postgresql/data

export TICKER="ticker-v1.1.0"
export TICKER_PATH="$TICKER-linux-amd64"
wget -O ticker.tar.gz https://github.com/diamnet/go/releases/download/$TICKER/$TICKER_PATH.tar.gz
tar -xvzf ticker.tar.gz
mv $TICKER_PATH/ticker /opt/diamnet/bin/ticker
chmod +x /opt/diamnet/bin/ticker
