version: '3'
services:
  aurora:
    environment:
      - HISTORY_ARCHIVE_URLS=https://history.diamnet.org/prd/core-live/core_live_001
      - NETWORK_PASSPHRASE=Public Global Diamnet Network ; September 2015
      - CAPTIVE_CORE_CONFIG_APPEND_PATH=/captive-core-pubnet.cfg
    volumes:
      - ./captive-core-pubnet.cfg:/captive-core-pubnet.cfg